#!/usr/bin/env python3
"""Render shared canonical files into plugins and repository templates; --check never writes."""

from __future__ import annotations

import argparse
import os
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MARKER_PREFIX = b"<!-- Generated by scripts/render-shared-files.py;"

# (canonical source, destination relative to each plugin root, plugins)
SHARED = (
    ("shared/review-core/review-criteria.md", "references/review-criteria.md", ("review", "dev-workflow")),
    ("shared/review-core/code-quality.md", "references/code-quality.md", ("review", "dev-workflow")),
    ("shared/review-core/javascript-typescript-review.md", "references/javascript-typescript-review.md", ("review", "dev-workflow")),
    ("shared/review-core/code-reviewer.md", "references/review/code-reviewer.md", ("review", "dev-workflow")),
    ("shared/review-core/responding-to-review.md", "references/responding-to-review.md", ("review", "dev-workflow", "git")),
    ("shared/review-core/review-package", "scripts/review-package", ("review", "dev-workflow")),
    ("shared/delivery-writing/tracker-prose.md", "references/tracker-prose.md", ("git", "tickets", "review")),
    ("shared/delivery-writing/writing-composition.md", "references/writing-composition.md", ("git", "tickets")),
    ("shared/delivery-writing/conventional-commits.md", "references/conventional-commits.md", ("git", "review")),
    ("shared/delivery-writing/media.md", "references/media.md", ("git", "tickets")),
    ("shared/delivery-writing/hosts.md", "references/hosts.md", ("git", "tickets", "review")),
)

# (source, destination) copied byte for byte into this repository.
REPOSITORY = (
    ("plugins/git/skills/write-pr/assets/templates/pull-request.md", ".github/pull_request_template.md"),
    ("plugins/tickets/skills/write-ticket/assets/github/ISSUE_TEMPLATE/1-bug.yml", ".github/ISSUE_TEMPLATE/1-bug.yml"),
    ("plugins/tickets/skills/write-ticket/assets/github/ISSUE_TEMPLATE/2-request.yml", ".github/ISSUE_TEMPLATE/2-request.yml"),
    ("plugins/tickets/skills/write-ticket/assets/github/ISSUE_TEMPLATE/config.yml", ".github/ISSUE_TEMPLATE/config.yml"),
)


def marker(source: str) -> bytes:
    return MARKER_PREFIX + f" edit {source}. -->\n".encode("utf-8")


def require_source(path: Path) -> None:
    if not path.is_file():
        raise SystemExit(f"error: missing canonical source {path.relative_to(ROOT)}")


def require_destination(path: Path) -> None:
    for parent in path.parents:
        if parent == ROOT:
            break
        if parent.exists() and not parent.is_dir():
            raise SystemExit(f"error: destination parent is a file: {parent.relative_to(ROOT)}")


def outputs() -> dict[Path, tuple[bytes, int]]:
    rendered: dict[Path, tuple[bytes, int]] = {}
    for source_name, destination_name, plugins in SHARED:
        source = ROOT / source_name
        require_source(source)
        data = source.read_bytes()
        if source.suffix == ".md":
            data = marker(source_name) + data
        mode = source.stat().st_mode & 0o777
        for plugin in plugins:
            destination = ROOT / "plugins" / plugin / destination_name
            require_destination(destination)
            rendered[destination] = (data, mode)
    for source_name, destination_name in REPOSITORY:
        source = ROOT / source_name
        require_source(source)
        destination = ROOT / destination_name
        require_destination(destination)
        rendered[destination] = (source.read_bytes(), source.stat().st_mode & 0o777)
    return rendered


def managed_outputs() -> set[Path]:
    managed: set[Path] = set()
    plugins = sorted({plugin for _, _, names in SHARED for plugin in names})
    for plugin in plugins:
        references = ROOT / "plugins" / plugin / "references"
        if references.is_dir():
            for path in references.rglob("*.md"):
                if path.is_file():
                    with path.open("rb") as handle:
                        if handle.readline().startswith(MARKER_PREFIX):
                            managed.add(path)
    for _, destination_name, names in SHARED:
        if destination_name.endswith(".md"):
            continue
        for plugin in names:
            path = ROOT / "plugins" / plugin / destination_name
            if path.is_file():
                managed.add(path)
    for _, destination_name in REPOSITORY:
        path = ROOT / destination_name
        if path.is_file():
            managed.add(path)
    return managed


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = outputs()
    stale: list[str] = []
    for path in sorted(managed_outputs() - set(rendered)):
        stale.append(str(path.relative_to(ROOT)))
        if not args.check:
            path.unlink()
    for path, (data, mode) in rendered.items():
        if path.is_file() and path.read_bytes() == data and path.stat().st_mode & 0o777 == mode:
            continue
        stale.append(str(path.relative_to(ROOT)))
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
            os.chmod(path, mode)
    for path in stale:
        print(("stale: " if args.check else "rendered: ") + path)
    return int(args.check and bool(stale))


if __name__ == "__main__":
    raise SystemExit(main())
