#!/usr/bin/env python3
"""Bundle canonical Writing genre guidance into independently installable Workflow."""
import argparse
import sys
from pathlib import Path

DEFAULT_ROOT = Path(__file__).resolve().parents[1]
SOURCE = Path("plugins/writing")
WORKFLOW = Path("plugins/workflow")
BANNER = b"<!-- Generated by scripts/render-writing.py"
# Both packages keep references/ and assets/ at the same depth: Markdown links
# remain valid without rewriting prose or depending on another installed plugin.
PROJECTIONS = {
    "skills/writing/references/tickets.md": "skills/to-ticket/references/ticket-writing.md",
    "skills/writing/references/pull-requests.md": "skills/to-pr/references/pr-writing.md",
    "skills/writing/assets/templates/default.md": "skills/to-ticket/assets/templates/default.md",
    "skills/writing/assets/templates/bug.md": "skills/to-ticket/assets/templates/bug.md",
    "skills/writing/assets/templates/investigation.md": "skills/to-ticket/assets/templates/investigation.md",
    "skills/writing/assets/templates/pull-request.md": "skills/to-pr/assets/templates/pull-request.md",
    "LICENSE": "WRITING_LICENSE.md",
}


def safe_path(root, relative):
    path = root
    for part in relative.parts:
        path = path / part
        if path.is_symlink():
            raise ValueError(f"projection path is a symlink: {path}")
    return path


def render(root, check=False):
    outputs = {}
    # Read and validate every source/destination before mutating any output.
    for source_name, target_name in PROJECTIONS.items():
        source = safe_path(root, SOURCE / source_name)
        if not source.is_file():
            raise ValueError(f"missing writing source: {source}")
        target = safe_path(root, WORKFLOW / target_name)
        header = f"<!-- Generated by scripts/render-writing.py from {SOURCE / source_name}; do not edit. -->\n\n"
        outputs[target] = header.encode() + source.read_bytes()

    obsolete = []
    directory = safe_path(root, WORKFLOW)
    for path in directory.rglob("*.md"):
        if path not in outputs and not path.is_symlink() and path.is_file():
            with path.open("rb") as stream:
                generated = stream.read(len(BANNER)) == BANNER
            if generated:
                obsolete.append(safe_path(root, path.relative_to(root)))

    stale = [path for path, data in outputs.items()
             if not path.is_file() or path.read_bytes() != data]
    if check:
        for path in stale:
            print(f"stale writing projection: {path.relative_to(root)}", file=sys.stderr)
        for path in obsolete:
            print(f"obsolete writing projection: {path.relative_to(root)}", file=sys.stderr)
        return int(bool(stale or obsolete))

    for path in stale:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(outputs[path])
        print(f"rendered {path.relative_to(root)}")
    for path in obsolete:
        path.unlink()
        print(f"removed obsolete projection {path.relative_to(root)}")
    return 0


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=DEFAULT_ROOT)
    parser.add_argument("--check", action="store_true", help="report drift without writing")
    args = parser.parse_args()
    try:
        return render(args.root.resolve(), args.check)
    except (OSError, ValueError) as error:
        print(error, file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
