#!/usr/bin/env python3
"""Package shared policy references for standalone plugins; --check is read-only."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "shared/agent-policy"


def outputs():
    data = json.loads((SOURCE / "profiles.json").read_text())
    roles = data["roles"]
    table = "| 역할 | 모델 | 추론 | 기본 인원 |\n| --- | --- | --- | --- |\n"
    table += "".join(f"| `{name}` | `{p['model']}` | `{p['effort']}` | {p['count']} |\n"
                     for name, p in roles.items())
    header = ("<!-- Generated by scripts/render-agent-policy.py; edit shared/agent-policy. -->\n"
              f"# 모델 프로필 v{data['version']}\n\n확인 날짜: {data['verified_at']}. "
              "현재 native 도구 스키마와 사용자 지정을 우선한다.\n\n")
    sources = "\n공식 근거: " + ", ".join(f"[출처 {i+1}]({url})" for i, url in enumerate(data["sources"])) + "\n"
    text = header + table + "\n" + (SOURCE / "prompt-deltas.md").read_text() + sources
    for plugin in ("engineering", "prompting"):
        yield ROOT / f"plugins/{plugin}/references/model-profiles.md", text.encode()
    yield ROOT / "plugins/engineering/references/model-profiles.json", (SOURCE / "profiles.json").read_bytes()
    claude = json.loads((SOURCE / "claude-profiles.json").read_text())
    claude_table = "| 역할 | 모델 | effort | 기본 인원 |\n| --- | --- | --- | --- |\n"
    claude_table += "".join(f"| `{name}` | `{p['model']}` | `{p['effort']}` | {p['count']} |\n"
                            for name, p in claude["roles"].items())
    claude_text = ("<!-- Generated by scripts/render-agent-policy.py; edit shared/agent-policy. -->\n"
                   f"# Claude Code 모델 프로필 v{claude['version']}\n\n"
                   f"확인 날짜: {claude['verified_at']}. 사용자 지정과 현재 native 도구 스키마가 우선한다.\n\n"
                   + claude_table + "\n" + (SOURCE / "claude-prompt-deltas.md").read_text()
                   + "\n공식 근거: " + ", ".join(f"[출처 {i+1}]({url})" for i, url in enumerate(claude["sources"])) + "\n")
    for plugin in ("engineering", "prompting"):
        yield ROOT / f"plugins/{plugin}/references/claude-model-profiles.md", claude_text.encode()
    yield ROOT / "plugins/engineering/references/claude-model-profiles.json", (SOURCE / "claude-profiles.json").read_bytes()
    authority = ("<!-- Generated by scripts/render-agent-policy.py; edit shared/agent-policy. -->\n" +
                 (SOURCE / "delivery-authority.md").read_text()).encode()
    for plugin in ("engineering", "workflow"):
        yield ROOT / f"plugins/{plugin}/references/delivery-authority.md", authority


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for path, data in outputs():
        if path.exists() and path.read_bytes() == data:
            continue
        stale.append(str(path.relative_to(ROOT)))
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
    for path in stale:
        print(("stale: " if args.check else "rendered: ") + path)
    return int(args.check and bool(stale))


if __name__ == "__main__":
    raise SystemExit(main())
