#!/usr/bin/env python3
"""Render self-contained design-quality contracts into design plugins."""

from __future__ import annotations

import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "shared" / "design-quality"
PLUGINS = ("interface-design", "operations-ui", "figma-workflow")
MARKER = b"<!-- Generated by scripts/render-design-quality.py; edit shared/design-quality. -->\n"


def outputs():
    reference = (
        MARKER.decode("utf-8")
        + (SOURCE / "design-quality.md")
        .read_text(encoding="utf-8")
        .replace("(sources.md)", "(design-quality-sources.md)")
    ).encode("utf-8")
    sources = (
        MARKER.decode("utf-8")
        + (SOURCE / "sources.md").read_text(encoding="utf-8")
    ).encode("utf-8")
    madia_method = (
        MARKER.decode("utf-8")
        + (ROOT / "docs" / "research" / "madia-design-practice-method.md").read_text(
            encoding="utf-8"
        )
    ).encode("utf-8")
    validator = (SOURCE / "validate_design_quality.py").read_bytes()
    for plugin in PLUGINS:
        root = ROOT / "plugins" / plugin
        yield root / "references" / "design-quality.md", reference
        yield root / "references" / "design-quality-sources.md", sources
        yield root / "references" / "madia-design-practice-method.md", madia_method
        yield root / "scripts" / "validate_design_quality.py", validator
        yield root / "scripts" / "design_md.mjs", (SOURCE / "design_md.mjs").read_bytes()
        for name in (
            "policy.json",
            "design-decision-contract.schema.json",
            "design-quality-report.schema.json",
        ):
            yield root / "assets" / "design-quality" / name, (SOURCE / name).read_bytes()
        if plugin == "operations-ui":
            yield root / "assets" / "screen-contract.schema.json", (
                SOURCE / "design-decision-contract.schema.json"
            ).read_bytes()
            yield root / "assets" / "quality-report.schema.json", (
                SOURCE / "design-quality-report.schema.json"
            ).read_bytes()


def managed_outputs() -> set[Path]:
    managed: set[Path] = set()
    for plugin in PLUGINS:
        root = ROOT / "plugins" / plugin
        asset_directory = root / "assets" / "design-quality"
        if asset_directory.exists():
            managed.update(path for path in asset_directory.iterdir() if path.is_file())
        for name in ("validate_design_quality.py", "design_md.mjs"):
            validator = root / "scripts" / name
            if validator.exists():
                managed.add(validator)
        reference_directory = root / "references"
        if reference_directory.exists():
            for path in reference_directory.iterdir():
                if path.is_file() and path.read_bytes().startswith(MARKER):
                    managed.add(path)
        if plugin == "operations-ui":
            managed.add(root / "assets" / "screen-contract.schema.json")
            managed.add(root / "assets" / "quality-report.schema.json")
    return managed


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = dict(outputs())
    stale: list[str] = []
    stale_extras = sorted(managed_outputs() - set(rendered))
    for path in stale_extras:
        stale.append(str(path.relative_to(ROOT)))
        if not args.check:
            path.unlink()
    for path, data in rendered.items():
        if path.exists() and path.read_bytes() == data:
            continue
        stale.append(str(path.relative_to(ROOT)))
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
    for path in stale:
        print(("stale: " if args.check else "rendered: ") + path)
    return int(args.check and bool(stale))


if __name__ == "__main__":
    raise SystemExit(main())
