#!/usr/bin/env python3
"""Package shared policy references for standalone plugins; --check is read-only."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "shared/agent-policy"
CODEX_PRIMARY_MODELS = ("gpt-6.1-sol", "gpt-6-astra")
CODEX_AGENT_MARKER = "# Generated by scripts/render-agent-policy.py; edit ROLE_DEFINITIONS there.\n"

ROLE_DEFINITIONS = {
    "extraction": (
        "Extracts requested facts and returns them in the requested structure.",
        "Extract only the specified facts from the assigned sources. Preserve source wording, "
        "identifiers, and uncertainty; cite the location of each result. Do not infer a design or "
        "make decisions from the extracted facts.",
        True,
    ),
    "exploration": (
        "Explores the assigned code or documents and gathers evidence.",
        "Trace the bounded question through the relevant sources. Return observed behavior, "
        "source locations, and unresolved questions without changing the artifact or choosing "
        "an implementation for the caller.",
        True,
    ),
    "localized_implementation": (
        "Implements a narrow, well-specified change and its focused verification.",
        "Make the assigned local change within the approved write scope. Check its direct "
        "consumers and run the focused verification in the brief. Return the diff, observed "
        "results, and any decision that would expand the scope.",
        False,
    ),
    "implementation": (
        "Implements the assigned change and verifies its behavior.",
        "Own the assigned implementation slice and its integration points within the approved "
        "write scope. Verify the resulting behavior and return the diff, observed results, "
        "unverified conditions, and decisions needed from the caller.",
        False,
    ),
    "complex_design": (
        "Analyzes a complex design boundary and returns evidence-backed options.",
        "Examine the assigned design boundary, constraints, dependencies, and failure cases. "
        "Return viable options, tradeoffs, a recommendation, and open contract decisions. "
        "Do not implement or treat an unresolved decision as approved.",
        True,
    ),
    "general_review": (
        "Independently reviews the complete assigned change with a fresh context.",
        "Review the fixed full artifact against the supplied requirements and criteria. "
        "Report actionable findings with location, trigger, impact, and evidence. Do not use "
        "the implementer's conclusions or another initial reviewer's findings as evidence.",
        True,
    ),
    "focused_review": (
        "Reviews only the assigned perspective or local correction.",
        "Review the specified issue, perspective, or correction against the fixed artifact and "
        "relevant prior evidence. Read surrounding material only to establish its effect on "
        "that scope. Report whether a changed contract or unclear impact requires full review.",
        True,
    ),
    "senior_review": (
        "Independently reviews the complete change as the higher-capability review slot.",
        "Review the same fixed full artifact and criteria as the general reviewers, "
        "independently. Examine cross-boundary assumptions and systemic failure paths as "
        "well as local defects. Do not adjudicate other reviewers' reports.",
        True,
    ),
    "adjudication": (
        "Checks a named reported finding against the evidence and contract.",
        "Test only the assigned disputed finding against the fixed artifact, reachable path, "
        "and governing contract. Return a supported, unsupported, or unresolved assessment "
        "with evidence; leave final integration and disposition to the caller.",
        True,
    ),
    "complex_adjudication": (
        "Checks a named finding across complex state, permission, or compatibility boundaries.",
        "Test the assigned disputed finding across the relevant state, permission, recovery, "
        "or compatibility boundary. Identify the concrete path and missing evidence, then "
        "return a supported, unsupported, or unresolved assessment to the caller.",
        True,
    ),
    "red_team": (
        "Challenges the completed work against its fixed goal and evidence.",
        "After the ordinary review, challenge whether the fixed whole-work bundle actually "
        "achieves the original goal. Seek concrete counterexamples and smaller solutions "
        "that preserve required behavior. Use the bundle's evidence and return its required "
        "verdict and return target; do not repair the work.",
        True,
    ),
}

COMMON_AGENT_INSTRUCTIONS = (
    "Follow the caller's task brief, revision, evidence, and read/write scope. Do not broaden "
    "the task or delegate further. Return the requested result and identify unverified "
    "settings or limitations."
)


def role_definition(role):
    description, instructions, read_only = ROLE_DEFINITIONS[role]
    if read_only:
        instructions += " Do not modify files."
    return description, instructions + "\n\n" + COMMON_AGENT_INSTRUCTIONS, read_only


def codex_agent(role):
    description, instructions, read_only = role_definition(role)
    lines = [
        CODEX_AGENT_MARKER.rstrip("\n"),
        f'name = {json.dumps(role)}',
        f'description = {json.dumps(description)}',
    ]
    if read_only:
        lines.append('sandbox_mode = "read-only"')
    lines.extend(['developer_instructions = """', instructions, '"""', ''])
    return ROOT / f".codex/agents/{role}.toml", "\n".join(lines).encode()


def claude_agent(plugin, role, profile):
    description, instructions, _ = role_definition(role)
    frontmatter = ["---", f"name: {role}", f'description: "{description}"', f"model: {profile['model']}"]
    if profile["effort"] != "inherit":
        frontmatter.append(f"effort: {profile['effort']}")
    content = "\n".join(frontmatter + [
        "---",
        "",
        instructions,
        "",
    ])
    return ROOT / f"plugins/{plugin}/agents/{role}.md", content.encode()


def pr_review_defaults(data):
    policy = data["pr_review"]
    if policy.get("settings_policy") == "inherit_native":
        return (
            "\n## PR 리뷰 기본값\n\n"
            f"PR 리뷰는 순정 `{policy['native_agent']}`를 라운드당 {policy['count']}명 새로 요청하며 "
            "model·effort·memory·isolation·동시성은 기존 omp 설정을 따른다. "
            "역할별 override나 설정 overlay를 기본 설치·실행의 조건으로 추가하지 않는다. "
            "위 legacy 역할 표는 순정 reviewer의 설정값이 아니며 기본 5개 배포에 적용하지 않는다. "
            "이전 결과를 제외한 새 입력, 지적 검증, 승인된 수정과 전체 재리뷰, 결과 보존과 "
            "소유한 임시 공간 정리는 조정자가 담당한다. 관측한 설정과 격리 한계를 기록하고 "
            "사용자가 다른 설정을 명시했을 때만 지원 범위 안에서 별도 실행에 적용한다.\n"
        )
    role = policy["role"]
    profile = {**data["roles"][role], **{key: policy[key] for key in ("model", "effort") if key in policy}}
    return (
        "\n## PR 리뷰 기본값\n\n"
        f"PR 리뷰는 `{role}`의 `{profile['model']}` / `{profile['effort']}`를 "
        f"라운드당 {policy['count']}명 요청한다. 위 역할 표의 인원은 PR 외 일반 리뷰·개발 게이트의 "
        "기본값이다. PR 인원은 `pr_review.count`를 적용하며 상위 검토를 자동 추가하지 않는다. "
        "새 세션·메모리 격리, 지적 검증, 승인된 수정과 전체 재리뷰는 Engineering의 "
        "PR 실행 계약을 따른다. 사용자 지정과 현재 native 지원 범위가 우선한다.\n"
    )


def outputs(codex_primary_model=None):
    profile_path = SOURCE / "profiles.json"
    profile_bytes = profile_path.read_bytes()
    data = json.loads(profile_bytes)
    roles = data["roles"]
    if codex_primary_model:
        changed = False
        for profile in roles.values():
            if profile["model"] in CODEX_PRIMARY_MODELS and profile["model"] != codex_primary_model:
                profile["model"] = codex_primary_model
                changed = True
        if changed:
            profile_bytes = (json.dumps(data, ensure_ascii=False, indent=2) + "\n").encode()
        yield profile_path, profile_bytes
    for role in roles:
        yield codex_agent(role)
    table = "| 역할 | 모델 | 추론 | 기본 인원 |\n| --- | --- | --- | --- |\n"
    table += "".join(f"| `{name}` | `{p['model']}` | `{p['effort']}` | {p['count']} |\n"
                     for name, p in roles.items())
    header = ("<!-- Generated by scripts/render-agent-policy.py; edit shared/agent-policy. -->\n"
              f"# 모델 프로필 v{data['version']}\n\n확인 날짜: {data['verified_at']}. "
              "현재 native 도구 스키마와 사용자 지정을 우선한다.\n\n")
    sources = "\n공식 근거: " + ", ".join(f"[출처 {i+1}]({url})" for i, url in enumerate(data["sources"])) + "\n"
    text = header + table + pr_review_defaults(data) + "\n" + (SOURCE / "prompt-deltas.md").read_text() + sources
    for plugin in ("engineering", "prompting"):
        yield ROOT / f"plugins/{plugin}/references/model-profiles.md", text.encode()
    yield ROOT / "plugins/engineering/references/model-profiles.json", profile_bytes
    claude = json.loads((SOURCE / "claude-profiles.json").read_text())
    claude_table = "| 역할 | 모델 | effort | 기본 인원 |\n| --- | --- | --- | --- |\n"
    claude_table += "".join(f"| `{name}` | `{p['model']}` | `{p['effort']}` | {p['count']} |\n"
                            for name, p in claude["roles"].items())
    claude_text = ("<!-- Generated by scripts/render-agent-policy.py; edit shared/agent-policy. -->\n"
                   f"# Claude Code 모델 프로필 v{claude['version']}\n\n"
                   f"확인 날짜: {claude['verified_at']}. 사용자 지정과 현재 native 도구 스키마가 우선한다.\n\n"
                   + claude_table + pr_review_defaults(claude) + "\n" + (SOURCE / "claude-prompt-deltas.md").read_text()
                   + "\n공식 근거: " + ", ".join(f"[출처 {i+1}]({url})" for i, url in enumerate(claude["sources"])) + "\n")
    for plugin in ("engineering", "prompting"):
        yield ROOT / f"plugins/{plugin}/references/claude-model-profiles.md", claude_text.encode()
        for role, profile in claude["roles"].items():
            yield claude_agent(plugin, role, profile)
    yield ROOT / "plugins/engineering/references/claude-model-profiles.json", (SOURCE / "claude-profiles.json").read_bytes()
    omp = json.loads((SOURCE / "omp-profiles.json").read_text())
    omp_table = "| 역할 | 모델 별칭 | effort | 기본 인원 |\n| --- | --- | --- | --- |\n"
    omp_table += "".join(f"| `{name}` | `{p['model']}` | `{p['effort']}` | {p['count']} |\n"
                         for name, p in omp["roles"].items())
    omp_text = ("<!-- Generated by scripts/render-agent-policy.py; edit shared/agent-policy. -->\n"
                f"# omp 모델 프로필 v{omp['version']}\n\n"
                f"확인 날짜: {omp['verified_at']}. 사용자 지정과 현재 native 도구 스키마가 우선한다.\n\n"
                + (SOURCE / "omp-prompt-deltas.md").read_text()
                + "\n## 선택 설치한 Engineering 역할 참고\n\n"
                + "아래 표는 legacy 호출자용 별칭·인원 참고이며 기존 설정에 추가할 override 목록이 아니다.\n\n"
                + omp_table + pr_review_defaults(omp)
                + "\n공식 근거: " + ", ".join(f"[출처 {i+1}]({url})" for i, url in enumerate(omp["sources"])) + "\n")
    yield ROOT / "plugins/engineering/references/omp-model-profiles.md", omp_text.encode()
    yield ROOT / "plugins/engineering/references/omp-model-profiles.json", (SOURCE / "omp-profiles.json").read_bytes()
    authority = ("<!-- Generated by scripts/render-agent-policy.py; edit shared/agent-policy. -->\n" +
                 (SOURCE / "delivery-authority.md").read_text()).encode()
    for plugin in ("engineering", "workflow"):
        yield ROOT / f"plugins/{plugin}/references/delivery-authority.md", authority
    branch_naming = ("<!-- Generated by scripts/render-agent-policy.py; edit shared/agent-policy. -->\n" +
                     (SOURCE / "branch-naming.md").read_text()).encode()
    for plugin in ("engineering", "workflow"):
        yield ROOT / f"plugins/{plugin}/references/branch-naming.md", branch_naming


def generated_agents():
    for path in (ROOT / ".codex/agents").glob("*.toml"):
        if path.read_bytes().startswith(CODEX_AGENT_MARKER.encode()):
            yield path
    for plugin in ("engineering", "prompting"):
        yield from (ROOT / "plugins" / plugin / "agents").glob("*.md")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--codex-primary-model", choices=CODEX_PRIMARY_MODELS,
                        help="Persist the model for existing Sol/Astra Codex roles and regenerate package references.")
    args = parser.parse_args()
    if args.check and args.codex_primary_model:
        parser.error("--check cannot be combined with --codex-primary-model")
    rendered = dict(outputs(args.codex_primary_model))
    codex_agent_dir = ROOT / ".codex/agents"
    marker = CODEX_AGENT_MARKER.encode()
    conflicts = []
    for path, data in rendered.items():
        if path.parent != codex_agent_dir or not path.exists():
            continue
        existing = path.read_bytes()
        if existing != data and not existing.startswith(marker):
            conflicts.append(path)
    if conflicts:
        for path in conflicts:
            print("conflict: " + str(path.relative_to(ROOT)))
        return 1

    stale = []
    for path in sorted(set(generated_agents()) - set(rendered)):
        stale.append(str(path.relative_to(ROOT)))
        if not args.check:
            path.unlink()
    for path, data in rendered.items():
        if path.exists() and path.read_bytes() == data:
            continue
        stale.append(str(path.relative_to(ROOT)))
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
    for path in stale:
        print(("stale: " if args.check else "rendered: ") + path)
    return int(args.check and bool(stale))


if __name__ == "__main__":
    raise SystemExit(main())
