#!/usr/bin/env python3
"""Package shared policy references for standalone plugins; --check is read-only."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "shared/agent-policy"
CODEX_AGENT_MARKER = "# Generated by scripts/render-agent-policy.py; edit ROLE_DEFINITIONS there.\n"

ROLE_DEFINITIONS = {
    "extraction": (
        "Extracts requested facts and returns them in the requested structure.",
        "Extract only the specified facts from the assigned sources. Preserve source wording, "
        "identifiers, and uncertainty; cite the location of each result. Do not infer a design or "
        "make decisions from the extracted facts.",
        True,
    ),
    "exploration": (
        "Explores the assigned code or documents and gathers evidence.",
        "Trace the bounded question through the relevant sources. Return observed behavior, "
        "source locations, and unresolved questions without changing the artifact or choosing "
        "an implementation for the caller.",
        True,
    ),
    "localized_implementation": (
        "Implements a narrow, well-specified change and its focused verification.",
        "Make the assigned local change within the approved write scope. Check its direct "
        "consumers and run the focused verification in the brief. Return the diff, observed "
        "results, and any decision that would expand the scope.",
        False,
    ),
    "implementation": (
        "Implements the assigned change and verifies its behavior.",
        "Own the assigned implementation slice and its integration points within the approved "
        "write scope. Verify the resulting behavior and return the diff, observed results, "
        "unverified conditions, and decisions needed from the caller.",
        False,
    ),
    "complex_design": (
        "Analyzes a complex design boundary and returns evidence-backed options.",
        "Examine the assigned design boundary, constraints, dependencies, and failure cases. "
        "Return viable options, tradeoffs, a recommendation, and open contract decisions. "
        "Do not implement or treat an unresolved decision as approved.",
        True,
    ),
    "general_review": (
        "Independently reviews the complete assigned change with a fresh context.",
        "Review the fixed full artifact against the supplied requirements and criteria. "
        "Report actionable findings with location, trigger, impact, and evidence. Do not use "
        "the implementer's conclusions or another initial reviewer's findings as evidence.",
        True,
    ),
    "focused_review": (
        "Reviews only the assigned perspective or local correction.",
        "Review the specified issue, perspective, or correction against the fixed artifact and "
        "relevant prior evidence. Read surrounding material only to establish its effect on "
        "that scope. Report whether a changed contract or unclear impact requires full review.",
        True,
    ),
    "senior_review": (
        "Independently reviews the complete change as the higher-capability review slot.",
        "Review the same fixed full artifact and criteria as the general reviewers, "
        "independently. Examine cross-boundary assumptions and systemic failure paths as "
        "well as local defects. Do not adjudicate other reviewers' reports.",
        True,
    ),
    "adjudication": (
        "Checks a named reported finding against the evidence and contract.",
        "Test only the assigned disputed finding against the fixed artifact, reachable path, "
        "and governing contract. Return a supported, unsupported, or unresolved assessment "
        "with evidence; leave final integration and disposition to the caller.",
        True,
    ),
    "complex_adjudication": (
        "Checks a named finding across complex state, permission, or compatibility boundaries.",
        "Test the assigned disputed finding across the relevant state, permission, recovery, "
        "or compatibility boundary. Identify the concrete path and missing evidence, then "
        "return a supported, unsupported, or unresolved assessment to the caller.",
        True,
    ),
    "red_team": (
        "Challenges the completed work against its fixed goal and evidence.",
        "After the ordinary review, challenge whether the fixed whole-work bundle actually "
        "achieves the original goal. Seek concrete counterexamples and smaller solutions "
        "that preserve required behavior. Use the bundle's evidence and return its required "
        "verdict and return target; do not repair the work.",
        True,
    ),
}

COMMON_AGENT_INSTRUCTIONS = (
    "Follow the caller's task brief, revision, evidence, and read/write scope. Do not broaden "
    "the task or delegate further. Return the requested result and identify unverified "
    "settings or limitations."
)


def role_definition(role):
    description, instructions, read_only = ROLE_DEFINITIONS[role]
    if read_only:
        instructions += " Do not modify files."
    return description, instructions + "\n\n" + COMMON_AGENT_INSTRUCTIONS, read_only


def codex_agent(role):
    description, instructions, read_only = role_definition(role)
    lines = [
        CODEX_AGENT_MARKER.rstrip("\n"),
        f'name = {json.dumps(role)}',
        f'description = {json.dumps(description)}',
    ]
    if read_only:
        lines.append('sandbox_mode = "read-only"')
    lines.extend(['developer_instructions = """', instructions, '"""', ''])
    return ROOT / f".codex/agents/{role}.toml", "\n".join(lines).encode()


def claude_agent(plugin, role, profile):
    description, instructions, _ = role_definition(role)
    frontmatter = ["---", f"name: {role}", f'description: "{description}"', f"model: {profile['model']}"]
    if profile["effort"] != "inherit":
        frontmatter.append(f"effort: {profile['effort']}")
    content = "\n".join(frontmatter + [
        "---",
        "",
        instructions,
        "",
    ])
    return ROOT / f"plugins/{plugin}/agents/{role}.md", content.encode()


def outputs():
    data = json.loads((SOURCE / "profiles.json").read_text())
    roles = data["roles"]
    for role in roles:
        yield codex_agent(role)
    table = "| 역할 | 모델 | 추론 | 기본 인원 |\n| --- | --- | --- | --- |\n"
    table += "".join(f"| `{name}` | `{p['model']}` | `{p['effort']}` | {p['count']} |\n"
                     for name, p in roles.items())
    header = ("<!-- Generated by scripts/render-agent-policy.py; edit shared/agent-policy. -->\n"
              f"# 모델 프로필 v{data['version']}\n\n확인 날짜: {data['verified_at']}. "
              "현재 native 도구 스키마와 사용자 지정을 우선한다.\n\n")
    sources = "\n공식 근거: " + ", ".join(f"[출처 {i+1}]({url})" for i, url in enumerate(data["sources"])) + "\n"
    text = header + table + "\n" + (SOURCE / "prompt-deltas.md").read_text() + sources
    for plugin in ("engineering", "prompting"):
        yield ROOT / f"plugins/{plugin}/references/model-profiles.md", text.encode()
    yield ROOT / "plugins/engineering/references/model-profiles.json", (SOURCE / "profiles.json").read_bytes()
    claude = json.loads((SOURCE / "claude-profiles.json").read_text())
    claude_table = "| 역할 | 모델 | effort | 기본 인원 |\n| --- | --- | --- | --- |\n"
    claude_table += "".join(f"| `{name}` | `{p['model']}` | `{p['effort']}` | {p['count']} |\n"
                            for name, p in claude["roles"].items())
    claude_text = ("<!-- Generated by scripts/render-agent-policy.py; edit shared/agent-policy. -->\n"
                   f"# Claude Code 모델 프로필 v{claude['version']}\n\n"
                   f"확인 날짜: {claude['verified_at']}. 사용자 지정과 현재 native 도구 스키마가 우선한다.\n\n"
                   + claude_table + "\n" + (SOURCE / "claude-prompt-deltas.md").read_text()
                   + "\n공식 근거: " + ", ".join(f"[출처 {i+1}]({url})" for i, url in enumerate(claude["sources"])) + "\n")
    for plugin in ("engineering", "prompting"):
        yield ROOT / f"plugins/{plugin}/references/claude-model-profiles.md", claude_text.encode()
        for role, profile in claude["roles"].items():
            yield claude_agent(plugin, role, profile)
    yield ROOT / "plugins/engineering/references/claude-model-profiles.json", (SOURCE / "claude-profiles.json").read_bytes()
    omp = json.loads((SOURCE / "omp-profiles.json").read_text())
    omp_table = "| 역할 | 모델 별칭 | effort | 기본 인원 |\n| --- | --- | --- | --- |\n"
    omp_table += "".join(f"| `{name}` | `{p['model']}` | `{p['effort']}` | {p['count']} |\n"
                         for name, p in omp["roles"].items())
    omp_config = ("```yaml\ntask:\n  agentModelOverrides:\n"
                  + "".join(f"    {name}: \"{p['model']}\"\n" for name, p in omp["roles"].items()) + "```\n")
    omp_text = ("<!-- Generated by scripts/render-agent-policy.py; edit shared/agent-policy. -->\n"
                f"# omp 모델 프로필 v{omp['version']}\n\n"
                f"확인 날짜: {omp['verified_at']}. 사용자 지정과 현재 native 도구 스키마가 우선한다.\n\n"
                + omp_table + "\n" + omp_config + "\n" + (SOURCE / "omp-prompt-deltas.md").read_text()
                + "\n공식 근거: " + ", ".join(f"[출처 {i+1}]({url})" for i, url in enumerate(omp["sources"])) + "\n")
    yield ROOT / "plugins/engineering/references/omp-model-profiles.md", omp_text.encode()
    yield ROOT / "plugins/engineering/references/omp-model-profiles.json", (SOURCE / "omp-profiles.json").read_bytes()
    authority = ("<!-- Generated by scripts/render-agent-policy.py; edit shared/agent-policy. -->\n" +
                 (SOURCE / "delivery-authority.md").read_text()).encode()
    for plugin in ("engineering", "workflow"):
        yield ROOT / f"plugins/{plugin}/references/delivery-authority.md", authority
    branch_naming = ("<!-- Generated by scripts/render-agent-policy.py; edit shared/agent-policy. -->\n" +
                     (SOURCE / "branch-naming.md").read_text()).encode()
    for plugin in ("engineering", "workflow"):
        yield ROOT / f"plugins/{plugin}/references/branch-naming.md", branch_naming


def generated_agents():
    for path in (ROOT / ".codex/agents").glob("*.toml"):
        if path.read_bytes().startswith(CODEX_AGENT_MARKER.encode()):
            yield path
    for plugin in ("engineering", "prompting"):
        yield from (ROOT / "plugins" / plugin / "agents").glob("*.md")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = dict(outputs())
    codex_agent_dir = ROOT / ".codex/agents"
    marker = CODEX_AGENT_MARKER.encode()
    conflicts = []
    for path, data in rendered.items():
        if path.parent != codex_agent_dir or not path.exists():
            continue
        existing = path.read_bytes()
        if existing != data and not existing.startswith(marker):
            conflicts.append(path)
    if conflicts:
        for path in conflicts:
            print("conflict: " + str(path.relative_to(ROOT)))
        return 1

    stale = []
    for path in sorted(set(generated_agents()) - set(rendered)):
        stale.append(str(path.relative_to(ROOT)))
        if not args.check:
            path.unlink()
    for path, data in rendered.items():
        if path.exists() and path.read_bytes() == data:
            continue
        stale.append(str(path.relative_to(ROOT)))
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
    for path in stale:
        print(("stale: " if args.check else "rendered: ") + path)
    return int(args.check and bool(stale))


if __name__ == "__main__":
    raise SystemExit(main())
